In [182]:
from pathlib import Path

import numpy as np
import pandas as pd
# DATA_PATH = Path.cwd().parent / "ML project" 
pd.set_option("display.max_columns", 100)
from sklearn.metrics import f1_score

In [183]:
train_df = pd.read_csv(
     "./train.csv", 
    index_col="tripid"
)

train_df['label'] = train_df['label'].map({"correct":1, "incorrect":0})
train_df_cols = train_df.columns.values
li = list(train_df_cols)
features_df = train_df[li[0:-1]]
labels_df = train_df[li[-1]]
features_df

,additional_fare,duration,meter_waiting,meter_waiting_fare,meter_waiting_till_pickup,pickup_time,drop_time,pick_lat,pick_lon,drop_lat,drop_lon,fare
tripid,,,,,,,,,,,,
189123628,10.5,834.0,56.0,0.0000,64.0,11/1/2019 0:20,11/1/2019 0:34,6.86252,79.8993,6.90330,79.8783,270.32
189125358,10.5,791.0,47.0,0.0000,134.0,11/1/2019 0:56,11/1/2019 1:09,6.88589,79.8984,6.91373,79.8923,197.85
189125719,10.5,1087.0,80.0,0.0000,61.0,11/1/2019 1:08,11/1/2019 1:26,6.90839,79.8651,6.93669,79.9146,301.64
189127273,10.5,598.0,271.0,15.6638,68.0,11/1/2019 2:27,11/1/2019 2:37,6.92570,79.8895,6.92748,79.8971,82.30
189128020,NaN,NaN,NaN,NaN,NaN,11/1/2019 3:34,11/1/2019 3:51,6.87441,79.8615,6.84478,79.9290,358.39
...,...,...,...,...,...,...,...,...,...,...,...,...
213803193,10.5,838.0,93.0,5.4219,451.0,1/31/2020 22:07,1/31/2020 22:21,7.29073,80.6367,7.28891,80.6557,198.26
213812756,10.5,2151.0,428.0,0.0000,39.0,1/31/2020 23:07,1/31/2020 23:43,6.90569,79.8516,6.95089,79.9389,581.23
213813930,10.5,263.0,9.0,0.0000,110.0,1/31/2020 23:21,1/31/2020 23:25,7.09210,79.9000,7.10135,79.9017,76.20
213815405,10.5,858.0,115.0,0.0000,317.0,1/31/2020 23:39,1/31/2020 23:53,6.94540,79.8768,6.93574,79.9010,133.31
213817296,10.5,262.0,21.0,1.2243,23.0,1/31/2020 23:49,1/31/2020 23:53,6.90257,79.9557,6.90823,79.9374,98.57

In [184]:
from math import sin, cos, sqrt, atan2, radians
def calculate_distance(**kwargs):
    R = 6373.0

    lat1 = radians(kwargs['pick_lat'])
    lon1 = radians(kwargs['pick_lon'])
    lat2 = radians(kwargs['drop_lat'])
    lon2 = radians(kwargs['drop_lon'])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c

In [185]:
def format_df(dataFrame):
    
    df = dataFrame
    df = df[~df.index.duplicated()]
    
    #calculatre the distance
    df['distance'] = [calculate_distance(**df[['pick_lat', 'pick_lon', 'drop_lat', 'drop_lon']].iloc[i].to_dict()) for i in range(df.shape[0])]
    
    #calculate the time difference between pickup and drop time in seconds
    df['time_difference'] = (pd.DatetimeIndex(df['drop_time']) - pd.DatetimeIndex(df['pickup_time'])).seconds
    
    #fill the missing values for the duration  
    df.loc[(pd.isnull(df.duration)), 'duration'] = df.time_difference

    #fill the missing values for additional_fare
    df.loc[(pd.isnull(df.additional_fare)), 'additional_fare'] = 13.719650642158596

    
    #fill the missing values for meter_waiting_till_pickup
    df.loc[(pd.isnull(df.meter_waiting_till_pickup)), 'meter_waiting_till_pickup'] = 112.466831624838

    
    #fill the missing values for meter_waiting
    df.loc[(pd.isnull(df.meter_waiting)), 'meter_waiting'] = 120
    
    #fill the missing values for meter_waiting_fare
    df.loc[(pd.isnull(df.meter_waiting_fare)), 'meter_waiting_fare'] = df.meter_waiting * 1.75/60

    #fill the missing values for fare
    df.loc[(pd.isnull(df.fare)), 'fare'] = df.meter_waiting_fare + df.additional_fare + df.distance

    df = df.drop(['pickup_time','drop_time','pick_lat','pick_lon','drop_lat','drop_lon'], axis = 1) 
    


    
    return df

In [186]:
newdf = format_df(features_df)
labels_df = labels_df[~labels_df.index.duplicated()]
newdf

C:\Users\X512\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\X512\anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\X512\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,additional_fare,duration,meter_waiting,meter_waiting_fare,meter_waiting_till_pickup,fare,distance,time_difference
tripid,,,,,,,,
189123628,10.500000,834.0,56.0,0.0000,64.000000,270.32,5.094369,840
189125358,10.500000,791.0,47.0,0.0000,134.000000,197.85,3.169052,780
189125719,10.500000,1087.0,80.0,0.0000,61.000000,301.64,6.307375,1080
189127273,10.500000,598.0,271.0,15.6638,68.000000,82.30,0.862217,600
189128020,13.719651,1020.0,120.0,3.5000,112.466832,358.39,8.150340,1020
...,...,...,...,...,...,...,...,...
213803193,10.500000,838.0,93.0,5.4219,451.000000,198.26,2.106037,840
213812756,10.500000,2151.0,428.0,0.0000,39.000000,581.23,10.871789,2160
213813930,10.500000,263.0,9.0,0.0000,110.000000,76.20,1.045847,240
213815405,10.500000,858.0,115.0,0.0000,317.000000,133.31,2.879981,840
213817296,10.500000,262.0,21.0,1.2243,23.000000,98.57,2.116539,240

In [187]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier

from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split

from sklearn.metrics import roc_curve, roc_auc_score

from sklearn.preprocessing import StandardScaler

RANDOM_SEED = 6

In [188]:
scaler = StandardScaler()
newdf[['additional_fare', 'duration','meter_waiting','meter_waiting_fare','meter_waiting_till_pickup','fare','distance','time_difference']] = scaler.fit_transform(newdf[['additional_fare', 'duration','meter_waiting','meter_waiting_fare','meter_waiting_till_pickup','fare','distance','time_difference']])
# numeric_cols = newdf.columns[newdf.dtypes != "object"].values

In [189]:
# # chain preprocessing into a Pipeline object
# # each step is a tuple of (name you chose, sklearn transformer)
# numeric_preprocessing_steps = Pipeline([
#     ('standard_scaler', StandardScaler()),
#     ('simple_imputer', SimpleImputer(strategy='median'))
# ])

# # create the preprocessor stage of final pipeline
# # each entry in the transformer list is a tuple of
# # (name you choose, sklearn transformer, list of columns)
# preprocessor = ColumnTransformer(
#     transformers = [
#         ("numeric", numeric_preprocessing_steps, numeric_cols)
#     ],
#     remainder = "drop"
# )

In [190]:
# estimators = estimator=LogisticRegression(penalty="l2", C=1)

In [191]:
# full_pipeline = Pipeline([
#     ("preprocessor", preprocessor),
#     ("estimators", estimators),
# ])

In [192]:
# full_pipeline
# None

In [208]:
X_train, X_eval, y_train, y_eval = train_test_split(
    newdf,
    labels_df,
    test_size=0.33,
    shuffle=True,
    stratify=labels_df,
    random_state=RANDOM_SEED
)

In [209]:
%%time

# # Train model
# full_pipeline.fit(X_train, y_train)

# # Predict on evaluation set
# # This competition wants probabilities, not labels
# preds = full_pipeline.predict(X_eval)
# y_preds = pd.DataFrame(
#     preds,
#     index = y_eval.index
# )
# f1 = f1_score(y_eval, y_preds)
# print(f1)

Wall time: 0 ns

In [210]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
pred = knn.predict(X_eval)
y_preds = pd.DataFrame(
    preds,
    index = y_eval.index
)
# print('Train accuracy score:',accuracy_score(y_train,y_pred))
# print('Test accuracy score:',accuracy_score(y_test,knn.predict(X_test)))
f1 = f1_score(y_eval, y_preds)
print(f1)

0.9492821182174156

In [211]:
#Importing MLPClassifier
from sklearn.neural_network import MLPClassifier

#Initializing the MLPClassifier
classifier = MLPClassifier(hidden_layer_sizes=(150,100,50), max_iter=300,activation = 'relu',solver='adam',random_state=1)

In [212]:
#Fitting the training data to the network
classifier.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(150, 100, 50), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=300,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [213]:
#Predicting y for X_val
y_pred = classifier.predict(X_eval)

In [214]:
#Importing Confusion Matrix
from sklearn.metrics import confusion_matrix
#Comparing the predictions against the actual observations in y_val
cm = confusion_matrix(y_pred, y_eval)

#Printing the accuracy
# print("Accuracy of MLPClassifier : '', accuracy(cm))
f1 = f1_score(y_eval, y_preds)
print(f1)

0.9492821182174156